# ------------------------------------------------------------------------------
# Proyecto: Mini Challenge 3 - Análisis de errores con selección dinámica
# Materia: Implementación de Robótica Inteligente
# Fecha: 22 de abril de 2025
# Alumnos:
#   - Jonathan Arles Guevara Molina  | A01710380
#   - Ezzat Alzahouri Campos         | A01710709
#   - José Ángel Huerta Ríos         | A01710607
#   - Ricardo Sierra Roa             | A01709887
# ------------------------------------------------------------------------------

# Grupos de errores
error_groups:
  - name: "error_1"
    waypoints:
      - {x: 0.0, y: 0.0}
      - {x: 1.2, y: 0.0}

  - name: "error_2"
    waypoints:
      - {x: 0.0, y: 0.0}
      - {x: -1.2, y: 0.0}

  - name: "error_3"
    waypoints:
      - {x: 0.0, y: 0.0}
      - {x: 0.0, y: 1.2}

  - name: "error_4"
    waypoints:
      - {x: 0.0, y: 0.0}
      - {x: 0.0, y: -1.2}

  - name: "error_5"
    waypoints:
      - {x: 0.0, y: 0.0}
      - {x: 1.2, y: 1.2}

  - name: "error_6"
    waypoints:
      - {x: 0.0, y: 0.0}
      - {x: -1.2, y: -1.2}
