# Tipo de definición de ruta: 'point_based', 'velocity_based' o 'time_based'
path_type: 'point_based'

# Velocidades máximas del robot (m/s y rad/s)
max_linear_speed: 0.3
max_angular_speed: 0.5

# Puntos de la ruta (coordenadas x,y en metros)
waypoints:
  - {x: 0.0, y: 0.0, linear_velocity: 0.2}
  - {x: 2.0, y: 0.0, linear_velocity: 0.2}
  - {x: 2.0, y: 2.0, linear_velocity: 0.2}
  - {x: 0.0, y: 2.0, linear_velocity: 0.2}
  - {x: 0.0, y: 0.0, linear_velocity: 0.2}

# Ejemplo para modo time_based:
# waypoints:
#   - {x: 0.0, y: 0.0, time: 5.0}
#   - {x: 2.0, y: 0.0, time: 10.0}