# Tipo de definición de ruta "time" o "speed"
path_type: time  

#target: 40 # segundos (si es "time") o m/s (si es "speed")
# Puntos de la ruta (coordenadas X y Y en metros)
#waypoints:
#  - {x: 1.0, y: 0.0}
#  - {x: 1.0, y: 1.0}
#  - {x: 0.0, y: 1.0}
#  - {x: 0.0, y: 0.0}

#target: 60  # segundos (si es "time") o m/s (si es "speed")
# Puntos de la ruta (coordenadas X y Y en metros)
#waypoints:
#  - {x: 1.0, y: 1.0}
#  - {x: 1.0, y: 0.3}
#  - {x: 0.5, y: 0.3}
#  - {x: 0.7, y: 1.2}

#Ejemplo de error
#path_type: time
target: 3  # segundos

waypoints:
  - {x: 0.0, y: 0.0}
  - {x: 1.5, y: 0.0}
  - {x: 1.5, y: 1.5}
  - {x: 0.0, y: 1.5}
  - {x: 0.0, y: 0.0}
