paths:
  straight:
    - {x: 0.0, y: 0.0}
    - {x: 0.55, y: 0.0}
  turn_right:
    - {x: 0.0, y: 0.0}
    - {x: 0.35, y: 0.0}
    - {x: 0.35, y: -0.25}
  turn_left:
    - {x: 0.0, y: 0.0}
    - {x: 0.35, y: 0.0}
    - {x: 0.35, y: 0.25}