# ------------------------------------------------------------------------------
# Proyecto: Puzzlebot Final Challenge - Paths Positions para Odoemetria
# Materia: Implementación de Robótica Inteligente
# Fecha: 14 de junio de 2025
# Alumnos:
#   - Jonathan Arles Guevara Molina  | A01710380
#   - Ezzat Alzahouri Campos         | A01710709
#   - José Ángel Huerta Ríos         | A01710607
#   - Ricardo Sierra Roa             | A01709887
# ------------------------------------------------------------------------------

paths:
  straight:
    - {x: 0.0, y: 0.0}
    - {x: 0.55, y: 0.0}
  turn_right:
    - {x: 0.0, y: 0.0}
    - {x: 0.25, y: 0.0}
    - {x: 0.25, y: -0.20}
  turn_left:
    - {x: 0.0, y: 0.0}
    - {x: 0.25, y: 0.0}
    - {x: 0.25, y: 0.20}